# Generated by Django 4.1.7 on 2023-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_name_element_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='username',
            field=models.CharField(default='Mathuschan', max_length=255),
        ),
    ]
